name: Deploy to Live Channel

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]
    types: [ closed ]
jobs:
  Deploy_Live_channel:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://gdsc-dju.web.app
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn build
      - run: yarn add babel-cli babel-preset-es2015 babel-preset-react babel-register react-router-sitemap
      - run: node sitemap-builder.js
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: run_firebase_deploy
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GDSC_DJU }}'
          channelId: live
          projectId: gdsc-dju
      - name: Discord Message Notify
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#4285f4"
          args: |
            gdsc-dju-web has been deployed to Live channel
            `Contributor` ${{github.actor}}
            `Event Status` ${{github.event_name}}
            `URL` https://gdsc-dju.web.app
            `Build Time` ${{steps.run_firebase_deploy.outputs.expire_time}}