## Workflow name
#name: 'Chromatic Deployment'
#
## Event for the workflow
#on:
#  push:
##    branches:
##      - master
##    paths:
##      - "packages/web/**"
##      - ".github/workflows/Docusaurus-deploy.yml"
##  pull_request:
##    branches:
##      - master
##    paths:
##      - "packages/web/**"
##      - ".github/workflows/Docusaurus-deploy.yml"
## List of jobs
#jobs:
#  storybook-build:
##    if: github.event.pull_request.merged == true
#    # Operating System
#    runs-on: ubuntu-latest
#    # Job steps
#    env:
#      working-directory: ./packages/web
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0 # ðŸ‘ˆ Required to retrieve git history
#      - name: Install dependencies
#        run: yarn
#        # ðŸ‘‡ Adds Chromatic as a step in the workflow
#      - name: Build SCT
#        run: yarn workspace @gdsc-dju/gds-theme build
#      - name: Build SC
#        run: yarn workspace @gdsc-dju/gds-ui build
#      - name: Publish to Chromatic
#        id: run_chromatic
#      - uses: chromaui/action@v1
#        # Options required to the GitHub Chromatic Action
#        with:
#          # ðŸ‘‡ Chromatic projectToken, refer to the manage page to obtain it.
#          workingDir: ${{ env.working-directory }}
#          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
#      - name: Discord Message Notify
#        uses: appleboy/discord-action@0.0.3
#        with:
#          webhook_id: ${{ secrets.DISCORD_DESIGN_WEBHOOK_ID }}
#          webhook_token: ${{ secrets.DISCORD_DESIGN_WEBHOOK_TOKEN }}
#          color: "#4285f4"
#          args: |
#            design-seed has been deployed
#            `Contributor` ${{github.actor}}
#            `url` ${{steps.run_chromatic.outputs.url}}
#            `storybookUrl` ${{steps.run_chromatic.outputs.storybookUrl}}
#
